apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gke-usage-metering-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gke-usage-metering-clusterrole
subjects:
- kind: ServiceAccount
  name: gke-usage-metering-sa
  namespace: kube-system