apiVersion: v1
kind: ResourceQuota
metadata:
  name: opa-resourcequota-example
  namespace: opa-resourcequota-example
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi