apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing

---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving

---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: ks
  namespace: knative-serving

---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: ke
  namespace: knative-eventing